CREATE TABLE ITEM
(
  ID            BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NAME          VARCHAR(255),
  AUCTION_END   DATETIME,
  INITIAL_PRICE DECIMAL(19, 2)
);

CREATE TABLE IMAGE
(
  ITEM_ID   BIGINT(20) NOT NULL,
  TITLE     VARCHAR(255),
  FILE_NAME VARCHAR(255),
  WIDTH     INT,
  HEIGHT    INT,
  CONSTRAINT FK_IMAGE2_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ID)
);

CREATE INDEX IDX_IMAGE_ITEM_ID
  ON IMAGE (ITEM_ID);


CREATE TABLE BID
(
  ID       BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  BID_DATE DATETIME,
  AMOUNT   DECIMAL(19, 2),
  ITEM_ID  BIGINT(20)             NOT NULL,
  CONSTRAINT FK_BID_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ID)
);

CREATE INDEX IDX_BID_ITEM_ID
  ON BID (ITEM_ID);

CREATE TABLE ITEM4
(
  ID            BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NAME          VARCHAR(255),
  AUCTION_END   DATETIME,
  INITIAL_PRICE DECIMAL(19, 2)
);

CREATE TABLE CATEGORY
(
  ID    BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  LABEL VARCHAR(255) NOT NULL
);

CREATE TABLE CATEGORY_ITEM4
(
  ITEM_ID     BIGINT(20) NOT NULL,
  CATEGORY_ID BIGINT(20) NOT NULL,
  CONSTRAINT FK_CATEGORY_ITEM4_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM4 (ID),
  CONSTRAINT FK_CATEGORY_ITEM4_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID)
);